name: CI Pipeline Evolved - Dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Job 1 - Build Image slim
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build avec nginx alpine slim
        run: docker build -t intranet-newdeal:slim .

  security-scan:
    name: Job 2 - Scan CRITICAL bloquant
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image slim
        run: docker build -t intranet-newdeal:slim .

      - name: Trivy - Bloquer si CRITICAL
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: intranet-newdeal:slim
          format: table
          exit-code: '1'
          severity: CRITICAL

  push:
    name: Job 3 - Push vers Docker Hub
    runs-on: ubuntu-latest
    needs: security-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build et Push image slim
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/intranet-newdeal:slim .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/intranet-newdeal:slim

  notify:
    name: Job 4 - Notification Email
    runs-on: ubuntu-latest
    needs: [build, security-scan, push]
    if: always()
    continue-on-error: true
    steps:
      - name: Envoyer email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "[CI/CD] Pipeline intranet-newdeal - ${{ job.status }}"
          to: moussawade@groupeisi.com
          from: ${{ secrets.MAIL_USERNAME }}
          body: |
            Pipeline execute sur branche dev.
            Statut : ${{ job.status }}
            Commit : ${{ github.sha }}
            Auteur : ${{ github.actor }}
